<?php

namespace ContainerX4wdrmx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAPISharepointControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\APISharepointController' shared autowired service.
     *
     * @return \App\Controller\APISharepointController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/APISharepointController.php';

        $container->services['App\\Controller\\APISharepointController'] = $instance = new \App\Controller\APISharepointController($container->getEnv('SP_WSDL'), $container->getEnv('SP_USERNAME'), $container->getEnv('SP_PASSWORD'), ($container->services['doctrine'] ?? $container->getDoctrineService()));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\APISharepointController', $container));

        return $instance;
    }
}
