<?php

namespace ContainerX4wdrmx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebCrawlerControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\WebCrawlerController' shared autowired service.
     *
     * @return \App\Controller\WebCrawlerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/WebCrawlerController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/BloomFilterService.php';

        $container->services['App\\Controller\\WebCrawlerController'] = $instance = new \App\Controller\WebCrawlerController(new \App\Service\BloomFilterService());

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\WebCrawlerController', $container));

        return $instance;
    }
}
