<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container91AX2NO\App_KernelLocalDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container91AX2NO/App_KernelLocalDebugContainer.php') {
    touch(__DIR__.'/Container91AX2NO.legacy');

    return;
}

if (!\class_exists(App_KernelLocalDebugContainer::class, false)) {
    \class_alias(\Container91AX2NO\App_KernelLocalDebugContainer::class, App_KernelLocalDebugContainer::class, false);
}

return new \Container91AX2NO\App_KernelLocalDebugContainer([
    'container.build_hash' => '91AX2NO',
    'container.build_id' => 'b5a05cc4',
    'container.build_time' => 1740662312,
], __DIR__.\DIRECTORY_SEPARATOR.'Container91AX2NO');
