<?php

namespace Container91AX2NO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTokenProviderService extends App_KernelLocalDebugContainer
{
    /**
     * Gets the private 'App\Security\TokenProvider' shared autowired service.
     *
     * @return \App\Security\TokenProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/UserProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Security/TokenProvider.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        if (isset($container->privates['App\\Security\\TokenProvider'])) {
            return $container->privates['App\\Security\\TokenProvider'];
        }

        return $container->privates['App\\Security\\TokenProvider'] = new \App\Security\TokenProvider($a, ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));
    }
}
