<?php

namespace ContainerNyhjCuV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestRedisTypeService extends App_KernelLocalDebugContainer
{
    /**
     * Gets the private 'App\Form\TestRedisType' shared autowired service.
     *
     * @return \App\Form\TestRedisType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/TestRedisType.php';

        return $container->privates['App\\Form\\TestRedisType'] = new \App\Form\TestRedisType();
    }
}
