<?php

namespace ContainerPoQUIfl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BJtQqmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bJt_qqm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bJt_qqm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\APISharepointController::synchroTeletravailValidors' => ['privates', '.service_locator.VmBCQmY', 'get_ServiceLocator_VmBCQmYService', true],
            'App\\Controller\\DemandController::index' => ['privates', '.service_locator.90baQdI', 'get_ServiceLocator_90baQdIService', true],
            'App\\Controller\\DemandController::indexOccasionnel' => ['privates', '.service_locator.90baQdI', 'get_ServiceLocator_90baQdIService', true],
            'App\\Controller\\DemandController::indexRegulier' => ['privates', '.service_locator.90baQdI', 'get_ServiceLocator_90baQdIService', true],
            'App\\Controller\\DemandController::indexResidence' => ['privates', '.service_locator.90baQdI', 'get_ServiceLocator_90baQdIService', true],
            'App\\Controller\\DemandController::notfound' => ['privates', '.service_locator.90baQdI', 'get_ServiceLocator_90baQdIService', true],
            'App\\Controller\\DemandController::search' => ['privates', '.service_locator.333XBmL', 'get_ServiceLocator_333XBmLService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\APISharepointController:synchroTeletravailValidors' => ['privates', '.service_locator.VmBCQmY', 'get_ServiceLocator_VmBCQmYService', true],
            'App\\Controller\\DemandController:index' => ['privates', '.service_locator.90baQdI', 'get_ServiceLocator_90baQdIService', true],
            'App\\Controller\\DemandController:indexOccasionnel' => ['privates', '.service_locator.90baQdI', 'get_ServiceLocator_90baQdIService', true],
            'App\\Controller\\DemandController:indexRegulier' => ['privates', '.service_locator.90baQdI', 'get_ServiceLocator_90baQdIService', true],
            'App\\Controller\\DemandController:indexResidence' => ['privates', '.service_locator.90baQdI', 'get_ServiceLocator_90baQdIService', true],
            'App\\Controller\\DemandController:notfound' => ['privates', '.service_locator.90baQdI', 'get_ServiceLocator_90baQdIService', true],
            'App\\Controller\\DemandController:search' => ['privates', '.service_locator.333XBmL', 'get_ServiceLocator_333XBmLService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\APISharepointController::synchroTeletravailValidors' => '?',
            'App\\Controller\\DemandController::index' => '?',
            'App\\Controller\\DemandController::indexOccasionnel' => '?',
            'App\\Controller\\DemandController::indexRegulier' => '?',
            'App\\Controller\\DemandController::indexResidence' => '?',
            'App\\Controller\\DemandController::notfound' => '?',
            'App\\Controller\\DemandController::search' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\APISharepointController:synchroTeletravailValidors' => '?',
            'App\\Controller\\DemandController:index' => '?',
            'App\\Controller\\DemandController:indexOccasionnel' => '?',
            'App\\Controller\\DemandController:indexRegulier' => '?',
            'App\\Controller\\DemandController:indexResidence' => '?',
            'App\\Controller\\DemandController:notfound' => '?',
            'App\\Controller\\DemandController:search' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
