<?php

namespace ContainerPoQUIfl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSynchroEmployeesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\SynchroEmployeesCommand' shared autowired service.
     *
     * @return \App\Command\SynchroEmployeesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/SynchroEmployeesCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Service/EmployeeService.php';

        $container->privates['App\\Command\\SynchroEmployeesCommand'] = $instance = new \App\Command\SynchroEmployeesCommand(new \App\Service\EmployeeService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['kernel'] ?? $container->get('kernel', 1)), ($container->privates['monolog.logger.doctrine'] ?? $container->getMonolog_Logger_DoctrineService()), ($container->services['cache.app'] ?? $container->getCache_AppService()), ($container->services['jms_serializer'] ?? $container->load('getJmsSerializerService'))));

        $instance->setName('app:synchro-employees');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
