<?php

namespace ContainerPoQUIfl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSynchroEmployeesCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\SynchroEmployeesCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\SynchroEmployeesCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:synchro-employees', [], 'Add a short description for your command', false, #[\Closure(name: 'App\\Command\\SynchroEmployeesCommand')] function () use ($container): \App\Command\SynchroEmployeesCommand {
            return ($container->privates['App\\Command\\SynchroEmployeesCommand'] ?? $container->load('getSynchroEmployeesCommandService'));
        });
    }
}
