<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX4wdrmx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX4wdrmx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX4wdrmx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX4wdrmx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX4wdrmx\App_KernelDevDebugContainer([
    'container.build_hash' => 'X4wdrmx',
    'container.build_id' => '4b56494a',
    'container.build_time' => 1741604989,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX4wdrmx');
